apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-node-deployment
  labels:
    app: kubernetes-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-node
  template:
    metadata:
      labels:
        app: kubernetes-node
    spec:
      containers:
      - name: kubernetes-node
        image: kubernetes-node:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
